### ISSUE TITLE
call to autostart raises ChangeError if service already started

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-operator#12]
I deployed loki from charmhub edge and after a while noticed the following recurring error in the log.
IIRC this was the reason I stopped used autostart in alertmanager.

```sh
unit-loki-0: 02:13:46 ERROR unit.loki/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 109, in <module>
    main(LokiOperatorCharm)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 409, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 769, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 79, in _on_loki_pebble_ready
    container.autostart()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1111, in autostart
    self._pebble.autostart_services()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 822, in autostart_services
    return self._services_action('autostart', [], timeout, delay)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 862, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (service "loki" was previously started)
```

**Comment by Abuelodelanada** [comment]
Fixed in #11
